spring:
  #?????
  datasource:
    url: jdbc:mysql://localhost:3306/takeoutfood?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 201388410
    driver-class-name: com.mysql.cj.jdbc.Driver